[package]
name = "rust-aoc"
version = "0.1.0"
authors = ["Joseph Richey <joerichey94@google.com>"]
edition = "2018"

[dependencies]
itertools = "0.7.11"
nom = "4.1.1"
bit-vec = "0.5.0"
intrusive-collections = "0.7.8"
euclid = "0.19.4"

[profile.release]
lto = true
